 version: "3"
 services:
   postgres-backuper:
     container_name: postgres-backup
     image: docker.io/suvitruf/postgres-backup:${PG_VERSION}
     environment:
       - PG_USER=${PG_USER}
       - PG_PASSWORD=${PG_PASSWORD}
       - PG_HOST=${PG_HOST}
       - PG_PORT=${PG_PORT}
       - PG_DB_NAME=${PG_DB_NAME}
       - PG_FORMAT=${PG_FORMAT}
       - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
       - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
       - S3_BUCKET=${S3_BUCKET}
       - S3_ENDPOINT=${S3_ENDPOINT}
       - IMMEDIATELY=${IMMEDIATELY}
       - TIMER=${TIMER}